name: First Workflow

on:
  - push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome to the world of CI/CD through GitHu Actions"

            - name: List all files including hidden files
              run: ls -1a

            - name: Show Present Working Directory 
              run: pwd