name: First Workflow

on:
  - push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "My first GitHu Actions Job"

            - name: List Files 
              run: ls 

            - name: Read file 
              run: cat dockerfile