name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"